'name': {'label': '権限名称', 'visibility': False},
'view_groupinterface': {'label': '権限グループ 参照権限', 'visibility': True},
'delete_groupinterface': {'label': '権限グループ 削除権限', 'visibility': True},
'change_groupinterface': {'label': '権限グループ 更新権限', 'visibility': True},
'add_groupinterface': {'label': '権限グループ 追加権限', 'visibility': True},
'view_permissioninterface': {'label': '権限情報 参照権限', 'visibility': True},
'delete_permissioninterface': {'label': '権限情報 削除権限', 'visibility': True},
'change_permissioninterface': {'label': '権限情報 更新権限', 'visibility': True},
'add_permissioninterface': {'label': '権限情報 追加権限', 'visibility': True},
'view_corporationuser': {'label': 'ユーザー 参照権限', 'visibility': True},
'delete_corporationuser': {'label': 'ユーザー 削除権限', 'visibility': True},
'change_corporationuser': {'label': 'ユーザー 更新権限', 'visibility': True},
'add_corporationuser': {'label': 'ユーザー 追加権限', 'visibility': True},
'view_userprofile': {'label': '-', 'visibility': False},
'delete_userprofile': {'label': '-', 'visibility': False},
'change_userprofile': {'label': '-', 'visibility': False},
'add_userprofile': {'label': '-', 'visibility': False},
'view_productlocation': {'label': '-', 'visibility': False},
'delete_productlocation': {'label': '-', 'visibility': False},
'change_productlocation': {'label': '-', 'visibility': False},
'add_productlocation': {'label': '-', 'visibility': False},
'view_allocationmanage': {'label': '引当管理 参照権限', 'visibility': True},
'delete_allocationmanage': {'label': '', 'visibility': False},
'change_allocationmanage': {'label': '引当管理 更新権限', 'visibility': True},
'add_allocationmanage': {'label': '', 'visibility': False},
'view_stock': {'label': '-', 'visibility': False},
'delete_stock': {'label': '-', 'visibility': False},
'change_stock': {'label': '-', 'visibility': False},
'add_stock': {'label': '-', 'visibility': False},
'view_shortage': {'label': '-', 'visibility': False},
'delete_shortage': {'label': '-', 'visibility': False},
'change_shortage': {'label': '-', 'visibility': False},
'add_shortage': {'label': '-', 'visibility': False},
'view_shippinginstruction': {'label': '-', 'visibility': False},
'delete_shippinginstruction': {'label': '-', 'visibility': False},
'change_shippinginstruction': {'label': '-', 'visibility': False},
'add_shippinginstruction': {'label': '-', 'visibility': False},
'view_allocation': {'label': '-', 'visibility': False},
'delete_allocation': {'label': '-', 'visibility': False},
'change_allocation': {'label': '-', 'visibility': False},
'add_allocation': {'label': '-', 'visibility': False},
'view_shopapisetting': {'label': '在庫参照/引当API設定 参照権限', 'visibility': True},
'delete_shopapisetting': {'label': '', 'visibility': False},
'change_shopapisetting': {'label': '', 'visibility': False},
'add_shopapisetting': {'label': '', 'visibility': False},
'view_shopsaleschannel': {'label': '販売チャネル情報 参照権限', 'visibility': True},
'delete_shopsaleschannel': {'label': '-', 'visibility': False},
'change_shopsaleschannel': {'label': '販売チャネル情報 更新権限', 'visibility': True},
'add_shopsaleschannel': {'label': '-', 'visibility': False},
'view_shop': {'label': '販売チャネル管理 参照権限', 'visibility': True},
'delete_shop': {'label': '販売チャネル管理 削除権限', 'visibility': True},
'change_shop': {'label': '販売チャネル管理 更新権限', 'visibility': True},
'add_shop': {'label': '販売チャネル管理 追加権限', 'visibility': True},
'view_locationgroupthresholdmanager': {'label': '-', 'visibility': False},
'delete_locationgroupthresholdmanager': {'label': '-', 'visibility': False},
'change_locationgroupthresholdmanager': {'label': '-', 'visibility': False},
'add_locationgroupthresholdmanager': {'label': '-', 'visibility': False},
'view_threshold': {'label': '閾値設定 参照権限', 'visibility': True},
'delete_threshold': {'label': '閾値設定 削除権限', 'visibility': True},
'change_threshold': {'label': '閾値設定 更新権限', 'visibility': True},
'add_threshold': {'label': '閾値設定 追加権限', 'visibility': True},
'view_timediffallocation': {'label': '-', 'visibility': False},
'delete_timediffallocation': {'label': '-', 'visibility': False},
'change_timediffallocation': {'label': '-', 'visibility': False},
'add_timediffallocation': {'label': '-', 'visibility': False},
'view_shoplocation': {'label': '-', 'visibility': False},
'delete_shoplocation': {'label': '-', 'visibility': False},
'change_shoplocation': {'label': '-', 'visibility': False},
'add_shoplocation': {'label': '-', 'visibility': False},
'view_priority': {'label': '-', 'visibility': False},
'delete_priority': {'label': '-', 'visibility': False},
'change_priority': {'label': '-', 'visibility': False},
'add_priority': {'label': '-', 'visibility': False},
'view_notallocatablecalendar': {'label': '-', 'visibility': False},
'delete_notallocatablecalendar': {'label': '-', 'visibility': False},
'change_notallocatablecalendar': {'label': '-', 'visibility': False},
'add_notallocatablecalendar': {'label': '-', 'visibility': False},
'view_locationgroupthreshold': {'label': '-', 'visibility': False},
'delete_locationgroupthreshold': {'label': '-', 'visibility': False},
'change_locationgroupthreshold': {'label': '-', 'visibility': False},
'add_locationgroupthreshold': {'label': '-', 'visibility': False},
'view_divide': {'label': '振り分け設定 参照権限', 'visibility': True},
'delete_divide': {'label': '振り分け設定 削除権限', 'visibility': True},
'change_divide': {'label': '振り分け設定 更新権限', 'visibility': True},
'add_divide': {'label': '振り分け設定 追加権限', 'visibility': True},
'view_attributethreshold': {'label': '-', 'visibility': False},
'delete_attributethreshold': {'label': '-', 'visibility': False},
'change_attributethreshold': {'label': '-', 'visibility': False},
'add_attributethreshold': {'label': '-', 'visibility': False},
'view_allocationavailability': {'label': '引当不可設定 参照権限', 'visibility': True},
'delete_allocationavailability': {'label': '引当不可設定 削除権限', 'visibility': True},
'change_allocationavailability': {'label': '引当不可設定 更新権限', 'visibility': True},
'add_allocationavailability': {'label': '引当不可設定 追加権限', 'visibility': True},
'view_product': {'label': '商品在庫管理 参照権限', 'visibility': True},
'delete_product': {'label': '', 'visibility': False},
'change_product': {'label': '商品在庫管理 更新権限', 'visibility': True},
'add_product': {'label': '商品在庫管理 追加権限', 'visibility': True},
'view_productsku': {'label': '-', 'visibility': False},
'delete_productsku': {'label': '-', 'visibility': False},
'change_productsku': {'label': '-', 'visibility': False},
'add_productsku': {'label': '-', 'visibility': False},
'view_manualmapping': {'label': '-', 'visibility': False},
'delete_manualmapping': {'label': '-', 'visibility': False},
'change_manualmapping': {'label': '-', 'visibility': False},
'add_manualmapping': {'label': '-', 'visibility': False},
'view_brand': {'label': 'ブランド情報 参照権限', 'visibility': True},
'delete_brand': {'label': '-', 'visibility': False},
'change_brand': {'label': '-', 'visibility': False},
'add_brand': {'label': '-', 'visibility': False},
'view_alertnotificationsetting': {'label': 'アラート通知設定 参照権限', 'visibility': True},
'delete_alertnotificationsetting': {'label': '-', 'visibility': False},
'change_alertnotificationsetting': {'label': 'アラート通知設定 更新権限', 'visibility': True},
'add_alertnotificationsetting': {'label': '-', 'visibility': False},
'view_alertadmin': {'label': 'アラート 参照権限 参照権限', 'visibility': True},
'delete_alertadmin': {'label': '-', 'visibility': False},
'change_alertadmin': {'label': '-', 'visibility': False},
'add_alertadmin': {'label': '-', 'visibility': False},
'view_notificationsetting': {'label': '-', 'visibility': False},
'delete_notificationsetting': {'label': '-', 'visibility': False},
'change_notificationsetting': {'label': '-', 'visibility': False},
'add_notificationsetting': {'label': '-', 'visibility': False},
'view_news': {'label': 'ニュース 参照権限', 'visibility': True},
'delete_news': {'label': 'ニュース 削除権限', 'visibility': True},
'change_news': {'label': 'ニュース 更新権限', 'visibility': True},
'add_news': {'label': 'ニュース 追加権限', 'visibility': True},
'view_alert': {'label': '-', 'visibility': False},
'delete_alert': {'label': '-', 'visibility': False},
'change_alert': {'label': '-', 'visibility': False},
'add_alert': {'label': '-', 'visibility': False},
'view_locationmanage': {'label': 'ロケーション管理 参照権限', 'visibility': True},
'delete_locationmanage': {'label': 'ロケーション管理 削除権限', 'visibility': True},
'change_locationmanage': {'label': 'ロケーション管理 更新権限', 'visibility': True},
'add_locationmanage': {'label': 'ロケーション管理 追加権限', 'visibility': True},
'view_locationgroup': {'label': '', 'visibility': False},
'delete_locationgroup': {'label': 'ロケーション管理内ロケーショングループ 削除権限', 'visibility': True},
'change_locationgroup': {'label': 'ロケーション管理内ロケーショングループ 更新権限', 'visibility': True},
'add_locationgroup': {'label': 'ロケーション管理内ロケーショングループ 追加権限', 'visibility': True},
'view_location': {'label': '-', 'visibility': False},
'delete_location': {'label': '-', 'visibility': False},
'change_location': {'label': '-', 'visibility': False},
'add_location': {'label': '-', 'visibility': False},
'view_sendstockinterface': {'label': '在庫データ送信IF 参照権限', 'visibility': True},
'delete_sendstockinterface': {'label': '在庫データ送信IF 削除権限', 'visibility': True},
'change_sendstockinterface': {'label': '在庫データ送信IF 更新権限', 'visibility': True},
'add_sendstockinterface': {'label': '在庫データ送信IF 追加権限', 'visibility': True},
'view_receivestockinterface': {'label': '在庫データ受信IF 参照権限', 'visibility': True},
'delete_receivestockinterface': {'label': '在庫データ受信IF 削除権限', 'visibility': True},
'change_receivestockinterface': {'label': '在庫データ受信IF 更新権限', 'visibility': True},
'add_receivestockinterface': {'label': '在庫データ受信IF 追加権限', 'visibility': True},
'view_allocatedatareceiveinterface': {'label': '引当データ受信IF 参照権限', 'visibility': True},
'delete_allocatedatareceiveinterface': {'label': '引当データ受信IF 削除権限', 'visibility': True},
'change_allocatedatareceiveinterface': {'label': '引当データ受信IF 更新権限', 'visibility': True},
'add_allocatedatareceiveinterface': {'label': '引当データ受信IF 追加権限', 'visibility': True},
'view_shippingresultdatareceiveinterface': {'label': '出荷結果データ受信IF 参照権限', 'visibility': True},
'delete_shippingresultdatareceiveinterface': {'label': '出荷結果データ受信IF 削除権限', 'visibility': True},
'change_shippingresultdatareceiveinterface': {'label': '出荷結果データ受信IF 更新権限', 'visibility': True},
'add_shippingresultdatareceiveinterface': {'label': '出荷結果データ受信IF 追加権限', 'visibility': True},
'view_sendshippinginstructioninterface': {'label': '出荷指示データ送信IF 参照権限', 'visibility': True},
'delete_sendshippinginstructioninterface': {'label': '出荷指示データ送信IF 削除権限', 'visibility': True},
'change_sendshippinginstructioninterface': {'label': '出荷指示データ送信IF 更新権限', 'visibility': True},
'add_sendshippinginstructioninterface': {'label': '出荷指示データ送信IF 追加権限', 'visibility': True},
'view_masterdatareceiveinterface': {'label': 'マスタデータ受信IF 参照権限', 'visibility': True},
'delete_masterdatareceiveinterface': {'label': 'マスタデータ受信IF 削除権限', 'visibility': True},
'change_masterdatareceiveinterface': {'label': 'マスタデータ受信IF 更新権限', 'visibility': True},
'add_masterdatareceiveinterface': {'label': 'マスタデータ受信IF 追加権限', 'visibility': True},
'view_sendreceiptrequest': {'label': '-', 'visibility': False},
'delete_sendreceiptrequest': {'label': '-', 'visibility': False},
'change_sendreceiptrequest': {'label': '-', 'visibility': False},
'add_sendreceiptrequest': {'label': '-', 'visibility': False},
'view_senddatainterface': {'label': '-', 'visibility': False},
'delete_senddatainterface': {'label': '-', 'visibility': False},
'change_senddatainterface': {'label': '-', 'visibility': False},
'add_senddatainterface': {'label': '-', 'visibility': False},
'view_receivedatainterface': {'label': '-', 'visibility': False},
'delete_receivedatainterface': {'label': '-', 'visibility': False},
'change_receivedatainterface': {'label': '-', 'visibility': False},
'add_receivedatainterface': {'label': '-', 'visibility': False},
'view_receiptrequestinterface': {'label': '入庫受入依頼IF 参照権限', 'visibility': True},
'delete_receiptrequestinterface': {'label': '入庫受入依頼IF 削除権限', 'visibility': True},
'change_receiptrequestinterface': {'label': '入庫受入依頼IF 更新権限', 'visibility': True},
'add_receiptrequestinterface': {'label': '入庫受入依頼IF 追加権限', 'visibility': True},
'view_diffcalculation': {'label': '-', 'visibility': False},
'delete_diffcalculation': {'label': '-', 'visibility': False},
'change_diffcalculation': {'label': '-', 'visibility': False},
'add_diffcalculation': {'label': '-', 'visibility': False},
'view_deadlinesetting': {'label': '締め処理設定 参照権限', 'visibility': True},
'delete_deadlinesetting': {'label': '締め処理設定 削除権限', 'visibility': True},
'change_deadlinesetting': {'label': '締め処理設定 更新権限', 'visibility': True},
'add_deadlinesetting': {'label': '締め処理設定 追加権限', 'visibility': True},
'view_connection': {'label': '受信元/送信先 参照権限', 'visibility': True},
'delete_connection': {'label': '受信元/送信先 削除権限', 'visibility': True},
'change_connection': {'label': '受信元/送信先 更新権限', 'visibility': True},
'add_connection': {'label': '受信元/送信先 追加権限', 'visibility': True},
'view_stockfluctuationhistory': {'label': '-', 'visibility': False},
'delete_stockfluctuationhistory': {'label': '-', 'visibility': False},
'change_stockfluctuationhistory': {'label': '-', 'visibility': False},
'add_stockfluctuationhistory': {'label': '-', 'visibility': False},
'view_filesendreceivehistory': {'label': '-', 'visibility': False},
'delete_filesendreceivehistory': {'label': '-', 'visibility': False},
'change_filesendreceivehistory': {'label': '-', 'visibility': False},
'add_filesendreceivehistory': {'label': '-', 'visibility': False},
'view_filedownloaduploadhistory': {'label': '-', 'visibility': False},
'delete_filedownloaduploadhistory': {'label': '-', 'visibility': False},
'change_filedownloaduploadhistory': {'label': '-', 'visibility': False},
'add_filedownloaduploadhistory': {'label': '-', 'visibility': False},
'view_batchhistory': {'label': '-', 'visibility': False},
'delete_batchhistory': {'label': '-', 'visibility': False},
'change_batchhistory': {'label': '-', 'visibility': False},
'add_batchhistory': {'label': '-', 'visibility': False},
'view_allocateapihistory': {'label': '-', 'visibility': False},
'delete_allocateapihistory': {'label': '-', 'visibility': False},
'change_allocateapihistory': {'label': '-', 'visibility': False},
'add_allocateapihistory': {'label': '-', 'visibility': False},
'view_saleschannel': {'label': '販売チャネル情報 参照権限', 'visibility': True},
'delete_saleschannel': {'label': '-', 'visibility': False},
'change_saleschannel': {'label': '-', 'visibility': False},
'add_saleschannel': {'label': '-', 'visibility': False},
'view_prefecture': {'label': '-', 'visibility': False},
'delete_prefecture': {'label': '-', 'visibility': False},
'change_prefecture': {'label': '-', 'visibility': False},
'add_prefecture': {'label': '-', 'visibility': False},
'view_domain': {'label': '-', 'visibility': False},
'delete_domain': {'label': '-', 'visibility': False},
'change_domain': {'label': '-', 'visibility': False},
'add_domain': {'label': '-', 'visibility': False},
'view_corporation': {'label': '法人情報 参照権限', 'visibility': True},
'delete_corporation': {'label': '-', 'visibility': False},
'change_corporation': {'label': '法人情報 更新権限', 'visibility': True},
'add_corporation': {'label': '-', 'visibility': False},
'view_apisetting': {'label': '-', 'visibility': False},
'delete_apisetting': {'label': '-', 'visibility': False},
'change_apisetting': {'label': '-', 'visibility': False},
'add_apisetting': {'label': '-', 'visibility': False},
'view_alerttype': {'label': '-', 'visibility': False},
'delete_alerttype': {'label': '-', 'visibility': False},
'change_alerttype': {'label': '-', 'visibility': False},
'add_alerttype': {'label': '-', 'visibility': False},
'view_socialtoken': {'label': '-', 'visibility': False},
'delete_socialtoken': {'label': '-', 'visibility': False},
'change_socialtoken': {'label': '-', 'visibility': False},
'add_socialtoken': {'label': '-', 'visibility': False},
'view_socialaccount': {'label': '-', 'visibility': False},
'delete_socialaccount': {'label': '-', 'visibility': False},
'change_socialaccount': {'label': '-', 'visibility': False},
'add_socialaccount': {'label': '-', 'visibility': False},
'view_socialapp': {'label': '-', 'visibility': False},
'delete_socialapp': {'label': '-', 'visibility': False},
'change_socialapp': {'label': '-', 'visibility': False},
'add_socialapp': {'label': '-', 'visibility': False},
'view_emailconfirmation': {'label': '-', 'visibility': False},
'delete_emailconfirmation': {'label': '-', 'visibility': False},
'change_emailconfirmation': {'label': '-', 'visibility': False},
'add_emailconfirmation': {'label': '-', 'visibility': False},
'view_emailaddress': {'label': '-', 'visibility': False},
'delete_emailaddress': {'label': '-', 'visibility': False},
'change_emailaddress': {'label': '-', 'visibility': False},
'add_emailaddress': {'label': '-', 'visibility': False},
'view_site': {'label': '-', 'visibility': False},
'delete_site': {'label': '-', 'visibility': False},
'change_site': {'label': '-', 'visibility': False},
'add_site': {'label': '-', 'visibility': False},
'view_session': {'label': '-', 'visibility': False},
'delete_session': {'label': '-', 'visibility': False},
'change_session': {'label': '-', 'visibility': False},
'add_session': {'label': '-', 'visibility': False},
'view_contenttype': {'label': '-', 'visibility': False},
'delete_contenttype': {'label': '-', 'visibility': False},
'change_contenttype': {'label': '-', 'visibility': False},
'add_contenttype': {'label': '-', 'visibility': False},
'view_group': {'label': '-', 'visibility': False},
'delete_group': {'label': '-', 'visibility': False},
'change_group': {'label': '-', 'visibility': False},
'add_group': {'label': '-', 'visibility': False},
'view_permission': {'label': '-', 'visibility': False},
'delete_permission': {'label': '-', 'visibility': False},
'change_permission': {'label': '-', 'visibility': False},
'add_permission': {'label': '-', 'visibility': False},
'view_logentry': {'label': '-', 'visibility': False},
'delete_logentry': {'label': '-', 'visibility': False},
'change_logentry': {'label': '-', 'visibility': False},
'add_logentry': {'label': '-', 'visibility': False},
'view_user': {'label': '-', 'visibility': False},
'delete_user': {'label': '-', 'visibility': False},
'change_user': {'label': '-', 'visibility': False},
'add_user': {'label': '-', 'visibility': False},
'view_permission': {'label': '-', 'visibility': False},
'delete_permission': {'label': '-', 'visibility': False},
'change_permission': {'label': '-', 'visibility': False},
'add_permission': {'label': '-', 'visibility': False},
'view_group': {'label': '-', 'visibility': False},
'delete_group': {'label': '-', 'visibility': False},
'change_group': {'label': '-', 'visibility': False},
'add_group': {'label': '-', 'visibility': False},
'view_allocation_dashboard': {'label': '引当データ集計 参照権限', 'visibility': True},
